sudo: required
services:
  - docker

script:
  - docker build -t marolt/configuration-server .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - docker push marolt/configuration-server